---
title: "gustiness"
author: "Naomi Lubkin"
output: html_document
date: '2022-07-01'
---
Gustiness Analaysis
Not really using anymore, but wanted to save it somewhere in case it comes up again. 

```{r}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
setwd("//wdc-fileserver/Staff/Summit/Interns/Naomi Lubkin/Wind and Humidity Climate Trends")
library(here)
here::here()
library(dplyr)
```

#Loading in data 
```{r}
#b16 peak daily gust speed and direction, jan 1935-dec 2021
peak_gust_dir <- read_csv(here("Data", "b16-peak gust speed and dir 1935-2021.csv"))

#b16 daily average wind speed (from hourly averages), jan 1935- dec 2021
daily_avg <-read_csv(here("Data", "b16-hourly daily wind average 1935-2021.csv")) 
daily_avg <- daily_avg %>%
  mutate(daily_avg_speed = as.numeric(daily_avg_speed), 
         daily_avg_spd = round(daily_avg_speed, digits = 1))
```

#analysis by month, looking into gustiness
```{r}
#gustiness here is ratio of peak gust: avg wind speed
#filtering peak daily gust dataset to include only dates after 1981
dailygust_81 <- peak_gust_dir %>%
  mutate(year=year(date), 
         date = as.Date(date))%>%
  filter(year>=1981)
#filtering daily average wind speed dataset to include only dates after 1981
dailyavg_81 <- daily_avg %>%
  mutate(date = as.Date(date), 
         year=year(date))%>%
  filter(year>=1981)
#merging peak daily gust and average daily wind datasets so I can compare them
gusts<-merge(dailygust_81, dailyavg_81, by="date")
#making a "gustiness" column that's the ratio of peak gust:average wind
gusts<- gusts %>%
  mutate(gustiness = peak_gust_speed/daily_avg_spd) %>%
  #select(date, peak_gust_speed, daily_avg_spd, gustiness) %>%
  mutate(month = month(date))

#ratio plotted... not super helpful as a visual (too many data points)
gustiness_plot <- gusts %>%
  ggplot(aes(x=date, y= gustiness)) +
  geom_point() +
  labs(x= "Date", y="Peak Daily Gust : Average Daily Wind Speed") +
  ggtitle ("Gustiness 1981-2021") +
  theme_minimal()
gustiness_plot




#Gustiness by month
#Nov
nov_gust <- gusts %>%
  filter(month==11)

nov_gust_plot <- nov_gust %>%
  ggplot(aes(x=date, y= gustiness)) +
  geom_point() +
  labs(x= "Date", y="Gustiness") +
  ggtitle ("November") +
  ylim(0, 15) +
  theme_minimal()
nov_gust_plot

#Dec
dec_gust <- gusts %>%
  filter(month == 12)

dec_gust_plot <- dec_gust %>%
  ggplot(aes(x=date, y= gustiness)) +
  geom_point() +
  labs(x= "Date", y="Gustiness") +
  ggtitle ("December") +
  ylim(0, 15) +
  theme_minimal()
dec_gust_plot

#Jan 
jan_gust <- gusts %>%
  filter(month == 1)

jan_gust_plot <- jan_gust %>%
  ggplot(aes(x=date, y= gustiness)) +
  geom_point() +
  labs(x= "Date", y="Gustiness") +
  ggtitle ("January") +
  ylim(0, 15) +
  theme_minimal()
jan_gust_plot

#Feb 
feb_gust <- gusts %>%
  filter(month == 2)

feb_gust_plot <- feb_gust %>%
  ggplot(aes(x=date, y= gustiness)) +
  geom_point() +
  labs(x= "Date", y="Gustiness") +
  ggtitle ("February") +
  ylim(0, 15) +
  theme_minimal()
feb_gust_plot


#Mar
mar_gust <- gusts %>%
  filter(month == 3)

mar_gust_plot <- mar_gust %>%
  ggplot(aes(x=date, y= gustiness)) +
  geom_point() +
  labs(x= "Date", y="Gustiness") +
  ggtitle ("March") +
  ylim(0, 15) +
  theme_minimal()
mar_gust_plot

#Apr
apr_gust <- gusts %>%
  filter(month == 4)

apr_gust_plot <- apr_gust %>%
  ggplot(aes(x=date, y= gustiness)) +
  geom_point() +
  labs(x= "Date", y="Gustiness") +
  ylim(0, 15) +
  ggtitle ("April") +
  theme_minimal()
apr_gust_plot

gustiness_NDJFMA_plot <-grid.arrange(nov_gust_plot, dec_gust_plot, jan_gust_plot, feb_gust_plot, mar_gust_plot, apr_gust_plot, 
                                nrow = 2, 
                                top = "Monthly Gustiness (Peak Daily Gust:Avg Daily Wind Speed) 1981-2021")
gustiness_NDJFMA_plot
```

