---
title: "Relative Humidity"
author: "Larz von Huene"
date: '2022-06-06'
output: html_document
---

# Packages and set working directory
```{r}
library(tidyverse)
#library(psychrolib)
library(lubridate)

knitr::opts_chunk$set(echo = TRUE)
setwd("//wdc-fileserver/Staff/Summit/Interns/Naomi Lubkin/Wind and Humidity Climate Trends")
```

# Load in Data
```{r, show_col_types = FALSE}
synoptic <- read_csv("//wdc-fileserver/Staff/Summit/Interns/Naomi Lubkin/Wind and Humidity Climate Trends/Data/b16 synoptic data 1935-2021.csv")
pres_weather <- read_csv("//wdc-fileserver/Staff/Summit/Interns/Naomi Lubkin/Wind and Humidity Climate Trends/Data/b16 hourly present weather split by code 1935-2021 (1).csv")
```
# Clean data
```{r}
synoptic <- synoptic %>% 
  filter(wet_bulb != "NULL" &  pressure_mb != "NULL") %>%  # removes all null values (from wet_bulb, dry_bulb, and pressure_mb)
  mutate(dry_bulb = as.numeric(dry_bulb), 
         wet_bulb = as.numeric(wet_bulb), 
         pressure_mb = as.numeric(pressure_mb), 
         precipitation = as.numeric(precipitation)) %>% # switch from chr to dbl
  filter(wet_bulb <= dry_bulb) # ensures that wet bulb is less than or equal to dry bulb for the sake of the RH equation

```


# Calculate Relative Humidity 
```{r}

# Calculations from WMO annex 4.B

# split data into ice and water (based on Seidel's distinction)
synoptic_rh_liquid <- synoptic %>% 
  filter(wet_bulb >= 32) 
synoptic_rh_ice <- synoptic %>% 
  filter(wet_bulb < 32)

## calculations 
# saturation vapor pressure
f_p_ice <- 1.0016+3.15*(10^-6)*(synoptic_rh_ice$pressure_mb)-0.074*(synoptic_rh_ice$pressure_mb)^-1 # function of pressure
f_p_water <- 1.0016+3.15*(10^-6)*(synoptic_rh_liquid$pressure_mb)-0.074*(synoptic_rh_liquid$pressure_mb)^-1

sat_vap_p_water_pure <- 6.112^(17.62*(synoptic_rh_liquid$dry_bulb)/(243.12+(synoptic_rh_liquid$dry_bulb))) # saturation vapor pressure for pure water
sat_vap_p_water_moist <- f_p_water*sat_vap_p_water_pure  # saturation vapor pressure for moist water
  
sat_vap_p_ice_pure <- 6.112^(22.46*(synoptic_rh_ice$dry_bulb)/(272.62+(synoptic_rh_ice$dry_bulb)))  # saturation vapor pressure for pure ice
sat_vap_p_ice_moist <- f_p_ice*sat_vap_p_ice_pure  # saturation vapor pressure for moist ice?

# Dew point and Frost point (not needed)


# psychometric formulas for the Assmann psychrometer
water_vap_p <- (6.112^(17.62*(synoptic_rh_liquid$wet_bulb)/(243.12+(synoptic_rh_liquid$wet_bulb))))*f_p_water - 6.53*(10^-4)*(1+0.000944*(synoptic_rh_liquid$wet_bulb))*(synoptic_rh_liquid$pressure_mb)*(synoptic_rh_liquid$dry_bulb - synoptic_rh_liquid$wet_bulb)

ice_vap_p <- (6.112^(17.62*(synoptic_rh_ice$wet_bulb)/(243.12+(synoptic_rh_ice$wet_bulb))))*f_p_ice - 6.53*(10^-4)*(1+0.000944*(synoptic_rh_ice$wet_bulb))*(synoptic_rh_ice$pressure_mb)*(synoptic_rh_ice$dry_bulb - synoptic_rh_ice$wet_bulb)

# Relative humidity
rh_liquid <- 100*water_vap_p/sat_vap_p_water_moist

rh_ice <- 100*ice_vap_p/sat_vap_p_ice_moist



# liquid tibble
synoptic_rh_liquid <- synoptic_rh_liquid %>% 
  mutate(RH = rh_liquid) 
synoptic_rh_liquid

# count how many negative values in "synoptic_RH_liquid"
nrow(synoptic_rh_liquid[synoptic_rh_liquid$RH<0,])
  # 0 negative out of 52,560 rows





# ice tibble: NEEDS FIXING
synoptic_rh_ice <- synoptic_rh_ice %>% 
  mutate(RH = rh_ice) 
synoptic_rh_ice

# count how many negative values in "synoptic_RH_ice"
nrow(synoptic_rh_ice[synoptic_rh_ice$RH<0,])
  # 3376 negative out of 70,874 rows

# percent with negative RH in "synoptic_RH_ice"
3376/70874 # 4.7%
```


# separate by seasons
```{r}
# seasons by month: so winter is 12 and 1-2, spring is 3-5, summer is 6-8, fall is 9-11
synoptic_rh_liquid <- synoptic_rh_liquid %>% 
  mutate(season = ifelse(between(month, 1, 2), "winter",
                         ifelse(month == 12, "winter", 
                                ifelse(between(month, 3, 5), "spring",
                                       ifelse(between(month, 6, 8), "summer",
                                              ifelse(between(month, 9, 11), "fall", NA))))))

season_rh <- synoptic_rh_liquid %>% 
  group_by(season, year) %>% 
  summarize(average_RH = mean(RH))
```

# Seasonal comparisons
```{r}
## Visual
season_rh %>% 
  ggplot(aes(year, average_RH, color = season)) +
  geom_point() +
  geom_smooth(method = lm) +
  facet_wrap(~season)


## Linear regression of seasonal data for all season 1935 - 2021, using seasonal averages

# fall
fall_rh <- season_rh %>% 
  filter(season == "fall") # isolate fall data

fall.lm = lm(average_RH ~ year, data = fall_rh)
summary(fall.lm)
# p-value  = 0.127
# adjusted r-squared = 0.01574


# spring
spring_rh <- season_rh %>% 
  filter(season == "spring") # isolate spring data

spring.lm = lm(average_RH ~ year, data = spring_rh)
summary(spring.lm)
# p-value  = 0.1129
# adjusted r-squared = 0.01789

# summer
summer_rh <- season_rh %>% 
  filter(season == "summer") # isolate summer data

summer.lm = lm(average_RH ~ year, data = summer_rh)
summary(summer.lm)
# p-value  = 0.02197
# adjusted r-squared = 0.04916

# winter
winter_rh <- season_rh %>% 
  filter(season == "winter") # isolate winter data

winter.lm = lm(average_RH ~ year, data = winter_rh)
summary(winter.lm)
# p-value  = 0.3717
# adjusted r-squared = -0.002254 

```



# Monthly comparisons, focusing on November 
```{r}
synoptic_rh_liquid <- synoptic_rh_liquid %>% 
  mutate(month = month(date), year = year(date))

month_rh <- synoptic_rh_liquid %>% 
  group_by(month, year) %>% 
  summarize(average_RH = mean(RH))

# overview of all months
ggplot(month_rh, aes(year, average_RH)) + geom_point() + geom_smooth(method = lm) + facet_wrap(~month)

# November
nov_rh <- month_rh %>% 
  filter(month == 11) 

ggplot(nov_rh, aes(year, average_RH)) + geom_point() + geom_smooth(method = lm)

nov.lm = lm(average_RH ~ year, data = nov_rh)
summary(nov.lm)
# p-value  = 0.64
# adjusted r-squared = -0.0093


# checking with Seidel 2007
synoptic_rh_liquid %>% 
  filter(year(date) <= 2004) %>% 
  summarize(avg = mean(RH))


synoptic_rh_liquid %>% 
  filter(year(date) <= 2004) %>% 
  filter(month(date) == 6 | month(date) == 7 | month(date) == 8) %>% # for JJA
  summarize(avg = mean(RH))



ggplot(synoptic_rh_liquid %>%  filter(year(date) <= 1940), aes(date, RH)) + geom_point()

ggplot(month_rh, aes(year, average_RH, col = as.factor(month))) + geom_point()
```


# Fog data 
```{r}
#sorting through present weather dataframe to select for hours with fog
hourly_fog <- pres_weather %>%
  mutate(fog= case_when(
    pw1 == "F" ~"F", 
    pw2 == "F" ~"F", 
    pw3 =="F" ~"F", 
    pw4 == "F" ~"F", 
    pw5 == "F" ~"F", 
    pw6 == "F" ~"F", 
    pw7 == "F" ~"F", 
    pw8 == "F" ~"F", 
    pw9 == "F" ~"F", 
    TRUE ~ "no_fog"))
hourly_fog <- hourly_fog %>%
  mutate(fake_fog = case_when (
    pw1 == "GF" ~ "Y", 
    pw2 == "GF" ~ "Y",
    pw3 == "GF" ~ "Y", 
    pw4 == "GF" ~ "Y", 
    pw5 == "GF" ~ "Y", 
    pw6 == "GF" ~ "Y", 
    pw7 == "GF" ~ "Y", 
    pw8 == "GF" ~ "Y", 
    pw9 == "GF" ~ "Y", 
    TRUE ~ "no_fake_fog")) 

#not sure why this isn't working
hourly_fog <- hourly_fog %>%
  mutate(true_fog = case_when (
    (fog == "F") & (fake_fog == "no_fake_fog") ~ "Y", 
    TRUE ~ as.character(NA))) 


dplyr::select(hourly_fog, date, true_fog)

```

