---
title: "Stage Office Analysis"
author: "Naomi Lubkin"
output: html_document
date: '2022-06-21'
---
Analysis on data set with wind speed data from both stage office and SA tower, 2020
Comparing the two to attempt to see if location plays a significant role in determining wind speed
CONCLUSION: Location does 
```{r setup, include=FALSE}
#loading in required packages
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
setwd("//wdc-fileserver/Staff/Summit/Interns/Naomi Lubkin/Wind and Humidity Climate Trends")
library(here)
here::here()
library(gamlss)
library(snht)
library(dplyr)

#loading in required data
stage_office_peak_5_sec_gusts <- read_csv(here("Data", "ft-tech-stage office peak 5 sec gusts.csv"))
```

##Cleaning/Manipulating the data
```{r}
#separating date out into individual components (easier to work with) and making all values numeric instead of character
stage_office <- stage_office_peak_5_sec_gusts %>%
  separate(date, c("month", "day", "year", "hour", "minute")) %>%
   mutate(rmyoung = as.numeric(rmyoung), 
         setra = as.numeric(setra), 
         foxboro = as.numeric(foxboro), 
         omega10 = as.numeric(omega10), 
         omega70 = as.numeric(omega70), 
         ventus = as.numeric(ventus), 
         ft742 = as.numeric(ft742)) 


#condensing month, day columns together and hour, minute columns together
stage_office$date <- paste(stage_office$month, stage_office$day, sep="-")
stage_office$time <- paste(stage_office$hour, stage_office$minute, sep="-")

#putting time/date columns together in format that's easier to work with, and narrowing dataframe to columns I'm actually using
stage_office$datetime <- paste(stage_office$date, stage_office$hour, sep='-')
stage_office <- stage_office %>%
  select(date, time, datetime, setra, foxboro, rmyoung, ventus, omega70, ft742, omega10)

#condensing data so that 6x per minute data is now averaged by  hour, 
#making NA's the right format,
#making everything all hours two digits so it formats correctly, 
#putting month, day columns together so I can sort by date later
stage_office_avgs_hr <- stage_office %>% 
  group_by(datetime) %>% 
  summarize(setra = mean(setra, na.rm = TRUE), 
            foxboro = mean(foxboro, na.rm = TRUE), 
            rmyoung=mean(rmyoung, na.rm = TRUE),
            omega10 = mean(omega10, na.rm = TRUE),
            omega70 = mean(omega70, na.rm = TRUE), 
            ft742 = mean(ft742, na.rm = TRUE)) %>%
  mutate(rmyoung = ifelse(rmyoung== "NaN", NA, rmyoung), 
         omega10 = ifelse(omega10== "NaN", NA, omega10)) %>%
  separate(datetime, c("month", "day", "hour")) %>%
  mutate(hour = case_when(hour == 0 ~ "00", 
                          hour == 1 ~ "01", 
                          hour == 2 ~ "02",
                          hour == 3 ~ "03",
                          hour == 4 ~ "04",
                          hour == 5 ~ "05",
                          hour == 6 ~ "06",
                          hour == 7 ~ "07",
                          hour == 8 ~ "08",
                          hour == 9 ~ "09", 
                          hour == 10 ~"10", 
                          hour == 11 ~"11",
                          hour == 12 ~"12",
                          hour == 13 ~"13",
                          hour == 14 ~"14",
                          hour == 15 ~"15",
                          hour == 16 ~"16",
                          hour == 17 ~"17",
                          hour == 18 ~"18",
                          hour == 19 ~"19",
                          hour == 20 ~"20",
                          hour == 21 ~"21",
                          hour == 22 ~"22",
                          hour == 23 ~"23",
                          hour == 24 ~"24")) %>%
  mutate(date = paste(month, day, sep="-"))

#calculating daily averages from hourly averages
#making missing values return as NA
#selecting columns I'm going to be using later
stage_office_avgs_day <- stage_office_avgs_hr%>%
  group_by(date) %>%
   summarize(setra = mean(setra, na.rm = TRUE), 
            foxboro = mean(foxboro, na.rm = TRUE), 
            rmyoung=mean(rmyoung, na.rm = TRUE),
            omega10 = mean(omega10, na.rm = TRUE),
            omega70 = mean(omega70, na.rm = TRUE), 
            ft742 = mean(ft742, na.rm = TRUE)) %>%
  mutate(rmyoung = ifelse(rmyoung== "NaN", NA, rmyoung), 
         omega10 = ifelse(omega10== "NaN", NA, omega10)) %>%
  select(date, setra, ft742, rmyoung, foxboro, omega10, omega70)

#"melting" data together so there's a column for Instrument, and Location
stage_office_melted <-melt(stage_office_avgs_day, id.var = c('date'), variable.name = 'Instrument') 
stage_office_melted <- stage_office_melted %>% 
  mutate(location = case_when(Instrument == "setra" ~ "Tower", 
                   Instrument == "rmyoung" ~ "Tower", 
                   Instrument == "foxboro" ~ "Tower", 
                   Instrument == "omega10" ~ "Tower",
                   Instrument == "omega70" ~ "Tower",
                   Instrument == "ft742" ~ "Stage", 
                   TRUE ~ NA_character_))
```

#Figures
```{r}
#Initial scatterplot
#for some reason the lines aren't showing up-- something wrong with geom_smooth?
stage_plot <- stage_office_melted %>%
  ggplot(aes(x=date, y= value, colour=Instrument)) +
  geom_point() +
  geom_smooth(formula= y~x, method="lm", se=FALSE) +
  labs(x="Date", y="Wind Speed (mph)") +
  theme_classic()
stage_plot
```

#Stats: Homogeneity tests
```{r}
#pairwise standard normal homogeneity test (snht) attempt
#is this even an appropriate test to be doing? 

#making a data frame for the snht
stage_snht <- stage_office_melted %>%
  rename(data=value) %>%
  select(data, location)

#location matrix for homogeneity test
matdata <- c(0, 349.5, 349.5, 0)
distmatrix <- matrix(matdata, nrow = 2, ncol=2, byrow=TRUE) 
rownames(distmatrix) <- c("Stage", "Tower")
colnames(distmatrix) <- c("Stage", "Tower")

#running the actual test
#NOTE: I have no idea what K, period, crit actually mean, which is why this test is not successful
SNHT_results <- pairwiseSNHT(stage_office_melted, distmatrix, k = 2, period = 10, crit = 100, returnStat=TRUE)
plotSNHT(stage_office_melted$data, stat=SNHT_results)

#making a txt file w elevation  info for homogeneity test
#this was for the homogen test, in climatol package, which I never successfully ran either
elevation <- data.frame(X = c(44.26999170073181, 44.27087013920043), 
                        Y = c(-71.30320763183697, -71.30347018488365), 
                        Z = c(1890, 1925.4), 
                        CODE = c("ft742", "setra"), 
                        NAME = c("Stage", "Tower"))
data <- stage_office_avgs_hr %>%
  
  

#homogen test attempt 
stage_plot.stats <- stage_office_melted %>%
  homogen('Instrument', 2020, 2020, expl=TRUE)
```

#Stats: ANOVA
```{r}
#two way ANOVA, where value (wind speed in mph) is modeled as a function of
#instrument (anemometer/sensor) and location (either stage office, or 
#sherman adams building tower)
stage_anova <- aov(value ~ location + Instrument, data = stage_office_melted)

summary(stage_anova)


```

