---
title: "Wind Threshold: above 22 mph"
author: "Naomi Lubkin"
output: html_document
date: '2022-06-29'
---
Filtering for events with fog and freezing temperatures, and wind speeds above 22 mph. 
There are separate rmd files for other wind thresholds. 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
setwd("//wdc-fileserver/Staff/Summit/Interns/Naomi Lubkin/Wind and Humidity Climate Trends")
library(here)
here::here()
library(dplyr)
library(lubridate)
library(gamlss)
library(gridExtra)
```

#Loading in the required data
```{r, echo=FALSE}
#b16 hourly present weather, split by code, jan 1935-dec 2021
pres_weather <- read_csv(here("Data", "b16 hourly present weather split by code 1935-2021 (1).csv"))

#b16 hourly daily wind speed, jan 1935-dec2021
hourly_wind <- read_csv(here("Data", "b16-hourly wind 1935-2021.csv")) 

hourly_temp <- read_csv("//wdc-fileserver.mwo.local/Staff/Summit/Interns/Naomi Lubkin/Wind and Humidity Climate Trends/Data/b16-hourly temperature 1935-2021.csv")
```

#Cleaning Data/ setting up required dataframes (GENERAL- for use w/ all thresholds)
```{r}
#sorting through present weather dataframe to select for hours with fog
hourly_fog <- pres_weather %>%
  mutate(fog= case_when(
    pw1 == "F" ~"F", 
    pw2 == "F" ~"F", 
    pw3 =="F" ~"F", 
    pw4 == "F" ~"F", 
    pw5 == "F" ~"F", 
    pw6 == "F" ~"F", 
    pw7 == "F" ~"F", 
    pw8 == "F" ~"F", 
    pw9 == "F" ~"F", 
    TRUE ~ as.character(NA))) %>%
  dplyr::select(date, fog)

#making data workable
xtrm_cond <- merge(hourly_fog, hourly_wind, by = 'date')
xtrm_cond <- merge(xtrm_cond, hourly_temp, by = 'date') 

#making dates correct data type
#separating into month, year column so that I can recombine columns into one with just month + year (so I can sort by that later)
xtrm_cond <- xtrm_cond %>%
  mutate(date = as.Date(date), 
         month=month(date), 
         year = year(date), 
         monyear = month + year) %>%
  na.omit()  %>% 
  mutate(windNumeric = as.numeric(wind_speed))


#combining year and month for analysis purposes
xtrm_cond$monyear <- str_c(xtrm_cond$month, "-", xtrm_cond$year)
```

#THRESHOLD: above 22 mph (1981-2021)
Setting up dataframe
```{r}
#making the dataframe
#Y in xtrm column means that that hour had fog, freezing temperatures, AND winds at or above 22 mph (meets all 3 requirements)
coldFog<-xtrm_cond %>%
filter(fog == "F" & temperature < 32 & year > 1980) 

above22 <- xtrm_cond %>%
  mutate(xtrm= case_when((fog=="F") & (wind_speed >= 22) & (temperature < 32) ~ "Y", 
         TRUE ~ as.character(NA)))



#counting number of times events w/ all 3 happen per year
#kinda just for funzies, not using for anything
count_above22 <- above22 %>% 
  count(year, xtrm)


#counting events by month, making a column with that count, filtering for years later than 1981
#filtering out all "NA" event counts, or times when 3 requirements not met
above22 <- above22 %>%
  count(monyear, xtrm) %>%
  separate(monyear, c("month", "year")) %>%
  filter(year>=1981, 
         xtrm == 'Y')
```

above 22 mph: sorting by month
```{r}
#Monthly trends: looking at each month separately (Nov-April)
#Nov
above22_nov <- above22 %>%
  filter(month == 11) %>%
  mutate(year=as.numeric(year), 
         month=as.numeric(month))
#Dec
above22_dec <- above22 %>%
  filter(month == 12)%>%
  mutate(year=as.numeric(year), 
         month=as.numeric(month))
#Jan
above22_jan <- above22 %>%
  filter(month == 1)%>%
  mutate(year=as.numeric(year), 
         month=as.numeric(month))
#Feb
above22_feb <- above22 %>%
  filter(month == 2)%>%
  mutate(year=as.numeric(year), 
         month=as.numeric(month))
#Mar
above22_mar <- above22 %>%
  filter(month == 3)%>%
  mutate(year=as.numeric(year), 
         month=as.numeric(month))
#Apr
above22_apr <- above22 %>%
  filter(month == 4)%>%
  mutate(year=as.numeric(year), 
         month=as.numeric(month))
#May
above22_may <- above22 %>%
  filter(month == 5)%>%
  mutate(year=as.numeric(year), 
         month=as.numeric(month))
#Jun
above22_jun <- above22 %>%
  filter(month == 6)%>%
  mutate(year=as.numeric(year), 
         month=as.numeric(month))

```

22 plots: overall and by month
```{r}
#overall 
above22_allmonths <- above22 %>%
  ggplot(aes(x=year, y=n)) +
  #geom_bar(stat= "identity") +
  geom_point() +
 # geom_smooth( se =FALSE, method = 'lm', show.legend = FALSE) +
  labs(x="Year", y="Number of Extreme Weather Events") +
  theme_minimal() 
above22_allmonths
#nov
above22_nov_plot <- above22_nov %>%
  ggplot(aes(x=year, y=n)) +
  geom_point() +
  geom_smooth(formula = y~x, se =FALSE, method = 'lm', show.legend = FALSE) +
  labs(x="Year", y="Number of Events") +
  theme(axis.text.x = element_text(angle = 60)) +
  ggtitle("November")


#dec
above22_dec_plot <- above22_dec %>%
  ggplot(aes(x=year, y=n)) +
  geom_point() +
  geom_smooth(formula = y~x, se =FALSE, method = 'lm', show.legend = FALSE) +
 labs(x="Year", y="Number of Events") +
  theme(axis.text.x = element_text(angle = 60)) +
  ggtitle("December")


#jan
above22_jan_plot <- above22_jan %>%
  ggplot(aes(x=year, y=n)) +
  geom_point() +
  geom_smooth(formula = y~x, se =FALSE, method = 'lm', show.legend = FALSE) +
  labs(x="Year", y="Number of Events") +
  theme(axis.text.x = element_text(angle = 60)) +
  ggtitle("January")


#feb
above22_feb_plot <- above22_feb %>%
  ggplot(aes(x=year, y=n)) +
  geom_point() +
  geom_smooth(formula = y~x, se =FALSE, method = 'lm', show.legend = FALSE) +
  labs(x="Year", y="Number of Events") +
  theme(axis.text.x = element_text(angle = 60)) +
  ggtitle("February")


#mar
above22_mar_plot <- above22_mar %>%
  ggplot(aes(x=year, y=n)) +
  geom_point() +
  geom_smooth(formula = y~x, se =FALSE, method = 'lm', show.legend = FALSE) +
  labs(x="Year", y="Number of Events") +
  theme(axis.text.x = element_text(angle = 60)) +
  ggtitle("March")


#apr
above22_apr_plot <- above22_apr %>%
  ggplot(aes(x=year, y=n)) +
  geom_point() +
  geom_smooth(formula = y~x, se =FALSE, method = 'lm', show.legend = FALSE) +
 labs(x="Year", y="Number of Events") +
  theme(axis.text.x = element_text(angle = 60)) +
  ggtitle("April")

#combined plot of extreme events for nov-apr, by individual month
above22_NovApr_plot <-grid.arrange(above22_nov_plot, above22_dec_plot, above22_jan_plot, above22_feb_plot, above22_mar_plot, above22_apr_plot, 
                                nrow = 2, 
                                top = "Fog, Freezing, and Above 22mph Events, 1981-2021")

```

22 stats
```{r}
###Overall 

###By month

##Nov
#fitting the distribution 
#Best fit: Double Poisson (AIC: 462.097)
fitDist(n,
        data = above22_nov, 
        type = "counts", 
        try.gamlss = T)
#model
mod_above22_nov <- gamlss(n~year, 
                       family = DPO(), 
                       data=above22_nov, 
                       control = gamlss.control())
#p-value: 0.788
summary(mod_above22_nov)


##Dec
#fitting the distribution 
#Best fit: Double Poisson (AIC: 446.364)
fitDist(n,
        data = above22_dec, 
        type = "counts", 
        try.gamlss = T)
#model
mod_above22_dec <- gamlss(n~year, 
                       family = DPO(), 
                       data=above22_dec, 
                       control = gamlss.control())
#p-value: 0.788
summary(mod_above22_dec)


##Jan
#fitting the distribution 
#Best fit: Negative binomial type II (NBII), AIC: 443.215
fitDist(n,
        data = above22_jan, 
        type = "counts", 
        try.gamlss = T)
#model
mod_above22_jan <- gamlss(n~year, 
                       family = NBII(), 
                       data=above22_jan, 
                       control = gamlss.control())
#p-value: 0.20992
summary(mod_above22_jan)


##Feb
#fitting the distribution 
#Best fit: double poisson (AIC: 448.278)
fitDist(n,
        data = above22_feb, 
        type = "counts", 
        try.gamlss = T)
#model
mod_above22_feb <- gamlss(n~year, 
                       family = DPO(), 
                       data=above22_feb, 
                       control = gamlss.control())
#p-value: 0.401
summary(mod_above22_feb)


##Mar
#fitting the distribution 
#Best fit: double poisson (AIC: 447.094)
fitDist(n,
        data = above22_mar, 
        type = "counts", 
        try.gamlss = T)
#model
mod_above22_mar <- gamlss(n~year, 
                       family = DPO(), 
                       data=above22_mar, 
                       control = gamlss.control())
#p-value: 0.675
summary(mod_above22_mar)


##Apr
#fitting the distribution 
#Best fit: double poisson (AIC: 442.415
fitDist(n,
        data = above22_apr, 
        type = "counts", 
        try.gamlss = T)
#model
mod_above22_apr <- gamlss(n~year, 
                       family = DPO(), 
                       data=above22_apr, 
                       control = gamlss.control())
#p-value: 0.930
summary(mod_above22_apr)
```

