---
title: "Wind Direction Stats"
author: "Naomi Lubkin"
date: "7/28/2023"
output: html_document
---
#Loading in libraries
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)

```


#Data: Loading in and cleaning
```{r}
hourly_direction <- read_csv("Data/b16-hourly wind speed plus direction 1935-2021.csv")


date1 <- ymd_hms("1970-05-04 00:55:00")
date2 <- ymd_hms("1970-07-09 23:55:00")

era1_start <- ymd_hms("1941-01-01 00:55:00")
era1_end <- ymd_hms("1980-05-30 23:55:00")
era2_start <- ymd_hms("1980-09-01 00:55:00")
era2_end <- ymd_hms("2022-12-31 23:55:00")

#homogonizing directions to 8 cardinal directions (first ~20 years have 16), then switching cardinal directions to degrees. Excluding May4-July 7 1970 (wind data taken from temporary location) and summer 1980 (switch to Sherman Adams Building occurred sometime in summer, but not sure when, so the whole season is excluded for simplicity)

hourly_dir <- hourly_direction %>%
  #mutate(date = as.POSIXct(date)) %>%
 # mutate(location = ifelse(date %within% interval(date1, date2) , "Shifting", "Stable")) %>% 
  #filter(location == "Stable") %>%
  mutate(era = ifelse(date %within% interval(date1, date2), NA, 
           ifelse(date %within% interval(era1_start, era1_end),"era1", 
                             ifelse(date %within% interval(era2_start, era2_end), "era2", NA)))) %>%
  mutate(simple_direction =  case_when( wind_direction == "WSW" ~ "SW", 
                                        wind_direction == "WNW" ~ "NW", 
                                        wind_direction == "NNW" ~ "NW",
                                        wind_direction == "NNE" ~ "NE",
                                        wind_direction == "ENE" ~ "NE",
                                        wind_direction == "ESE" ~ "SE",
                                        wind_direction == "SSE" ~ "SE",
                                        wind_direction == "SSW" ~ "SW", 
                                        wind_direction == "N" ~ "N",
                                        wind_direction == "NE" ~ "NE",
                                        wind_direction == "E" ~ "E",
                                        wind_direction == "SE" ~ "SE",
                                        wind_direction == "S" ~ "S",
                                        wind_direction == "SW" ~ "SW",
                                        wind_direction == "W" ~ "W",
                                        wind_direction == "NW" ~ "NW", 
                                        wind_direction == "00" ~ "N")) %>%
    dir_degree = case_when(simple_direction == "N" ~ 0,
                         simple_direction == "NE" ~ 45,
                         simple_direction == "E" ~ 90,
                         simple_direction == "SE" ~ 135,
                         simple_direction == "S" ~ 180,
                         simple_direction == "SW" ~ 225,
                         simple_direction == "W" ~ 270,
                         simple_direction == "NW" ~ 315) %>%
  rename(dir_compass = simple_direction) %>%
  select(date, dir_compass, dir_degree, wind_speed, era) %>%
  mutate(year = year(date), 
         month = month(date)) %>%
  filter(year >= 1941) %>%
  mutate(season = case_when(month == 12 ~  "Winter", 
                            month == 1 ~ "Winter", 
                            month == 2 ~  "Winter", 
                            month == 3 ~  "Spring",
                            month == 4 ~  "Spring",
                            month == 5 ~  "Spring",
                            month == 6 ~ "Summer",
                            month == 7 ~ "Summer",
                            month == 8 ~ "Summer",
                            month == 9  ~ "Fall", 
                            month == 10  ~ "Fall", 
                            month == 11  ~ "Fall"))




```

#Statistics
##**need strange wind directions (V, DI, 00) cleared up before doing wind direction stats
```{r}
# t-test: time period  (1941-1980; 1980-2022) and wind direction 
t.test(dir_degree ~ era, data = hourly_dir, var.equal = TRUE)
#t = 19.891, p-value < 2.2e-16
#era1: 240.9760          era2: 236.9551 

# ANOVA: wind direction and season
wind.dir.anova <- aov(dir_degree ~ era * season, data = hourly_dir)
summary(wind.dir.anova)
TukeyHSD(wind.dir.anova)
```

#Plot
```{r}
ggplot(data = hourly_dir, aes(x = date, y = dir_degree)) +
  geom_point(aes(colour=era))

test_plot<- ggplot(data = hourly_dir, aes(x = date, y = dir_compass)) +
  geom_point() +
  facet_wrap(~era)
```

