---
title: "Wind_Data_NL"
output: html_document
author: "Naomi Lubkin"
date: '2022-06-01'
---
This rmd contains a seasonal wind analysis that we didn't end up going any farther with, as well as wind plots/sens slopes for both 1935-2021 and 1981-2021 wind data broken down by month. 

#set up and loading packages, setting working directory
```{r setup, include=FALSE}


library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
setwd("//wdc-fileserver/Staff/Summit/Interns/Naomi Lubkin/Wind and Humidity Climate Trends")
library(here)
here::here()
library(lubridate)
library(dplyr)
#library(tibbletime)
library(openair) #for wind rose
#library(climaemet)
library(reshape2)
library(mblm)

library(robslopes)
library(gridExtra)
library(trend) #for sen slope function
library(stringr)
library(climatol) #for homogenization test
#library(fitdistrplus) #maybe don't need
library(gamlss)
library(snht)
library(stats)
```
#loading in data
```{r}
#ALL DATA from data folder 

#b16 peak daily gust speed and direction, jan 1935-dec 2021
peak_gust_dir <- read_csv(here("Data", "b16-peak gust speed and dir 1935-2021.csv"))

#b16 daily wind speed summary, jan 1935- dec 2021
daily_sum <- read_csv(here("Data", "b16 daily wind sum 1935-2021.csv"))

#b16 hourly present weather, split by code, jan 1935-dec 2021
#likely needs cleaning
pres_weather <- read_csv(here("Data", "b16 hourly present weather split by code 1935-2021 (1).csv"))

#b16 synoptic data jan 1935-dec 2021
#3x daily dry bulb temp, wet bulb temp, pressure, and precipitation
synoptic <- read_csv(here("Data", "b16 synoptic data 1935-2021.csv"))

#b16 hourly daily wind speed, jan 1935-dec2021
hourly_wind <- read_csv(here("Data", "b16-hourly wind 1935-2021.csv")) 


#b16 daily average wind speed (from hourly averages), jan 1935- dec 2021
daily_avg <-read_csv(here("Data", "b16-hourly daily wind average 1935-2021.csv")) 
         
         
#b16 monthly average wind speed (from hourly averages), jan 1935- dec 2021
monthly_avg <- read_csv(here("Data", "b16-hourly monthly wind average 1935-2021.csv"))


#b16 yearly average wind speed (from hourly averages), jan 1935- dec 2021
yearly_avg <-read_csv(here("Data", "b16-hourly yearly wind average 1935-2021.csv"))

#get some metadata for this one
stage_office_peak_5_sec_gusts <- read_csv(here("Data", "ft-tech-stage office peak 5 sec gusts.csv"))

#hourly speed and direction 1935-2021
hourly_spd_dir <- read_csv("//wdc-fileserver.mwo.local/Staff/Summit/Interns/Naomi Lubkin/Wind and Humidity Climate Trends/Data/b16-hourly wind speed plus direction 1935-2021.csv")

hourly_temp <- read_csv("//wdc-fileserver.mwo.local/Staff/Summit/Interns/Naomi Lubkin/Wind and Humidity Climate Trends/Data/b16-hourly temperature 1935-2021.csv")


```
#Cleaning data
```{r}
#Switiching data type from character to numeric, rounding to 1 decimal to match B16 values
#Note: NAs introduced in daily when switching data type to numeric were "NULL" in original dataset
daily_avg <- daily_avg %>%
  mutate(daily_avg_speed = as.numeric(daily_avg_speed), 
         daily_avg_spd = round(daily_avg_speed, digits = 1))

monthly_avg <- monthly_avg %>%
  mutate(monthly_avg_speed = as.numeric(monthly_avg_speed), 
         monthly_avg_spd = round(monthly_avg_speed, digits = 1), 
         date = as.Date(date), 
         month = month(date), 
         year =year(date))

yearly_avg <- yearly_avg %>%
  mutate(year_avg_speed = as.numeric(year_avg_speed), 
         year_avg_spd = round(year_avg_speed, digits = 1), 
         year = year(date), 
         year = as.numeric(year), 
         group = case_when (year <= 1940 ~ "1", 
                            year %in% 1941:1980 ~ "2", 
                            year >= 1981 ~ "3", 
                            TRUE ~ NA_character_))

# making a column grouping monthly data into seasons for seasonal analysis 
# also adding a column converting mph to m/s to compare to Cronin 
seasonal_winds <- monthly_avg %>%
  mutate(year = year(date), month=month(date), 
         year = as.numeric(year), 
         month = as.numeric(month), 
         season = case_when(
           month == 12 ~ "Winter",
            month == 1 ~ "Winter",
            month == 2 ~ "Winter",
           month == 3 ~ "Spring",
           month == 4 ~ "Spring",
           month == 5 ~ "Spring",
           month == 6 ~ "Summer",
           month == 7 ~ "Summer",
           month == 8 ~ "Summer",
           month == 9 ~ "Fall",
           month == 10 ~ "Fall",
           month == 11~ "Fall",
           TRUE ~ NA_character_)) %>%
  mutate(monthly_spd_ms = monthly_avg_spd*0.44704)
```


  
```{r}

#yearly data by year so theil-sen slopes are easier to calculate
#1935-1940
yearly_pre41 <- yearly_avg %>%
  filter(year<=1940) %>%
  mutate(date=as.Date(date), 
         year_avg_spd=as.numeric(year_avg_spd))
#1941-1981
yearly_41to80 <-yearly_avg %>%
  filter(year %in% 1941:1980) %>%
  mutate(date=as.Date(date), 
         year_avg_spd=as.numeric(year_avg_spd))
#1981-2021
yearly_since81 <- yearly_avg %>%
  filter(year>=1981) %>%
  mutate(date=as.Date(date), 
         year_avg_spd=as.numeric(year_avg_spd))

#for Theil Sen, grouping monthly averages since 1981 by season 
monthly_winter <- seasonal_winds %>%
  filter(season == "Winter", 
         year>=1981) 

monthly_spring <- seasonal_winds %>%
  filter(season == "Spring", 
         year>=1981)

monthly_summer <- seasonal_winds %>%
  filter(season == "Summer", 
         year>=1981)

monthly_fall <- seasonal_winds %>%
  filter(season == "Fall", 
         year>=1981)

#all seasons since 1981
monthly_since81 <- seasonal_winds %>%
  filter(year>= 1981)

#all seasons 1981-2013 (to check my values against Cronin)
monthly_81to13 <- monthly_since81 %>%
  filter(year<=2013)
```

#Additive Time Series Analysis
```{r}
#for additive time series analysis
#monthly 1935-2021
monthly_avg_decomp <- monthly_avg %>%
  mutate (year = year(date), 
          month = month(date)) %>%
  select(year, month, monthly_avg_spd)
monthly_avg_decomp <- ts(monthly_avg_decomp$monthly_avg_spd, frequency=12)
decomp <- decompose(monthly_avg_decomp)
plot(decomp)

#monthly 1981-2021
monthly_decomp_81 <- monthly_since81 %>%
  select(year, month, monthly_avg_spd)
monthly_decomp_81 <- ts(monthly_decomp_81$monthly_avg_spd, frequency=12)
decomp81 <- decompose(monthly_decomp_81)
plot(decomp81)
  
 

```

#Plotting
```{r}

#monthly average wind speed by season  
monthlyavg_season_plot <- ggplot(seasonal_winds, aes (x = year, y=monthly_avg_spd, colour = season)) + 
  geom_point() +
  geom_smooth(se=FALSE, method = 'loess')+
  labs( x = 'Year', y = 'Wind Speed (mph)') + 
  ggtitle("MWO Annual Wind Averages by Season") +
  theme_minimal() +
  ylim (0, 50) +
  xlim(1981, 2021)

monthlyavg_season_plot


# Annual wind averages 1935-2021 , with linear regression lines fitted to each period of wind observations (Figure 17 in Cronin)
#NOTE: need to do linear regression significance tests on these lines! 
annual_avg_plot <- yearly_avg %>%
  ggplot(aes (x = year, 
              y = year_avg_spd, 
              colour = group)) +
  geom_point (show.legend = FALSE) +
  geom_line(show.legend = FALSE)+
  geom_smooth( se =FALSE, method = 'lm', show.legend = FALSE) +
  ylim(0,50) +
  xlim(1935, 2021) +
  theme_minimal() +
  ggtitle ("MWO Annual Wind Averages 1935-2021") +
  labs (x= "Year", y = "Wind Speed (mph)")
  
annual_avg_plot


#plot of just winter (DJF) monthly averages 1981-2021
#find a way to average by year? tough because of Dec being in the previous year, so I"m not sure how to code
#has a line fitted to it, but linear regression model (below; winter.lm) has a non-significant p-value so line isn't really appropriate
winter_plot <- monthly_winter %>%
  ggplot(aes(x = year, 
             y = monthly_avg_spd)) +
  geom_point(colour = "blue") +
  ylim(0,70) +
  labs (x = "Year", y = "Wind Speed (mph)") +
  ggtitle("Winter (DJF) Wind Speeds 1981-2021") +
  theme_minimal() +
  geom_smooth( se =FALSE, method = 'lm', show.legend = FALSE) 

winter_plot

#plot of just spring (MAM) monthly averages 1981-2021
#can average by year, but I figured I'd leave it like this to match winter plot
#has a line fitted to it, but linear regression model (below; spring.lm) has a non-significant p-value so line isn't really appropriate
spring_plot <- monthly_spring %>%
  ggplot(aes(x = year, 
             y = monthly_avg_spd)) +
  geom_point(colour = "purple") +
  ylim(0,70) +
  labs (x = "Year", y = "Wind Speed (mph)") +
  ggtitle("'Spring' (MAM) Wind Speeds 1981-2021") +
  theme_minimal() +
  geom_smooth( se =FALSE, method = 'lm', show.legend = FALSE) 
  

spring_plot

overall_since81_plot <- yearly_since81 %>%
  ggplot(aes(x=year, y=year_avg_spd))+
  geom_point()+
  labs( x = "Year", y = "Wind Speed (mph)") +
  ggtitle("Yearly Average Wind Speeds 1981-2021") +
  ylim(0,50) +
  theme_minimal()
```

 

# Wind Analysis by Month, Using Monthly Averages
```{r}
###WINTER!
##November (11)
#making the data easier to work with (filtering by month, year)
just_nov <- monthly_avg %>%
  filter(month == 11)
just_nov_81 <- just_nov %>%
  filter(year>=1981)
  
  
#plot of Nov averages 1935-2021
november_plot_35 <- just_nov %>%
  ggplot(aes(x = date, y = monthly_avg_spd ))+
  geom_point() +
  ylim(0,55) +
  labs (x = "Year", y = "Wind Speed (mph)") +
  ggtitle("November Wind Speeds 1935-2021") +
  theme_minimal() +
  geom_smooth( se =FALSE, method = 'lm', show.legend = FALSE) 
november_plot_35

#plot of Nov averages 1981-2021
november_plot_81 <- just_nov_81 %>%
  ggplot(aes(x = date, y = monthly_avg_spd ))+
  geom_point() +
  ylim(0,55) +
  labs (x = "Year", y = "Wind Speed (mph)") +
  ggtitle("November") +
  theme_minimal() +
  geom_smooth( se =FALSE, method = 'lm', show.legend = FALSE) 
november_plot_81

##December (12)
#making the data easier to work with (filtering by month, year)
just_dec <- monthly_avg %>%
  filter(month == 12)
just_dec_81 <- just_dec %>%
  filter(year>=1981)
#plot of Dec averages 1935-2021
december_plot_35 <- just_dec %>%
  ggplot(aes(x = date, y = monthly_avg_spd ))+
  geom_point() +
  ylim(0,55) +
  labs (x = "Year", y = "Wind Speed (mph)") +
  ggtitle("December Wind Speeds 1935-2021") +
  theme_minimal() +
  geom_smooth( se =FALSE, method = 'lm', show.legend = FALSE) 
december_plot_35

#plot of Dec averages 1981-2021
december_plot_81 <- just_dec_81 %>%
  ggplot(aes(x = date, y = monthly_avg_spd ))+
  geom_point() +
  ylim(0,55) +
  labs (x = "Year", y = "Wind Speed (mph)") +
  ggtitle("December") +
  theme_minimal() +
  geom_smooth( se =FALSE, method = 'lm', show.legend = FALSE) 
december_plot_81

##January (1)
#making the data easier to work with (filtering by month, year)
just_jan <- monthly_avg %>%
  filter(month == 1)
just_jan_81 <- just_jan %>%
  filter(year>=1981)
#plot of Jan averages 1935-2021
january_plot_35 <- just_jan %>%
  ggplot(aes(x = date, y = monthly_avg_spd ))+
  geom_point() +
  ylim(0,55) +
  labs (x = "Year", y = "Wind Speed (mph)") +
  ggtitle("January Wind Speeds 1935-2021") +
  theme_minimal() +
  geom_smooth( se =FALSE, method = 'lm', show.legend = FALSE) 
january_plot_35

#plot of Jan averages 1981-2021
january_plot_81 <- just_jan_81 %>%
  ggplot(aes(x = date, y = monthly_avg_spd ))+
  geom_point() +
  ylim(0,55) +
  labs (x = "Year", y = "Wind Speed (mph)") +
  ggtitle("January") +
  theme_minimal() +
  geom_smooth( se =FALSE, method = 'lm', show.legend = FALSE) 
january_plot_81

##February (2)
#making the data easier to work with (filtering by month, year)
just_feb <- monthly_avg %>%
  filter(month == 2)
just_feb_81 <- just_feb %>%
  filter(year>=1981)
#plot of Feb averages 1935-2021
february_plot_35 <- just_feb %>%
  ggplot(aes(x = date, y = monthly_avg_spd ))+
  geom_point() +
  ylim(0,55) +
  labs (x = "Year", y = "Wind Speed (mph)") +
  ggtitle("February Wind Speeds 1935-2021") +
  theme_minimal() +
  geom_smooth( se =FALSE, method = 'lm', show.legend = FALSE) 
february_plot_35

#plot of Feb averages 1981-2021
february_plot_81 <- just_feb_81 %>%
  ggplot(aes(x = date, y = monthly_avg_spd ))+
  geom_point() +
  ylim(0,55) +
  labs (x = "Year", y = "Wind Speed (mph)") +
  ggtitle("February") +
  theme_minimal() +
  geom_smooth( se =FALSE, method = 'lm', show.legend = FALSE) 
february_plot_81

winter_NDJF_plot <-grid.arrange(november_plot_81, december_plot_81, january_plot_81, february_plot_81, 
                                nrow = 2, 
                                top = "'Winter' Wind Speeds 1981-2021")
winter_NDJF_plot


################################################################################
#SPRING
#March (3)
#making the data easier to work with (filtering by month, year)
just_mar <- monthly_avg %>%
  filter(month == 3)
just_mar_81 <- just_mar %>%
  filter(year>=1981)
  
  
#plot of March averages 1935-2021
march_plot_35 <- just_mar %>%
  ggplot(aes(x = date, y = monthly_avg_spd ))+
  geom_point() +
  ylim(0,55) +
  labs (x = "Year", y = "Wind Speed (mph)") +
  ggtitle("March Wind Speeds 1935-2021") +
  theme_minimal() +
  geom_smooth( se =FALSE, method = 'lm', show.legend = FALSE) 
march_plot_35

#plot of March averages 1981-2021
march_plot_81 <- just_mar_81 %>%
  ggplot(aes(x = date, y = monthly_avg_spd ))+
  geom_point() +
  ylim(0,55) +
  labs (x = "Year", y = "Wind Speed (mph)") +
  ggtitle("March") +
  theme_minimal() +
  geom_smooth( se =FALSE, method = 'lm', show.legend = FALSE) 
march_plot_81

#April (4)
#making the data easier to work with (filtering by month, year)
just_apr <- monthly_avg %>%
  filter(month == 4)
just_apr_81 <- just_apr %>%
  filter(year>=1981)
  
  
#plot of April averages 1935-2021
april_plot_35 <- just_apr %>%
  ggplot(aes(x = date, y = monthly_avg_spd ))+
  geom_point() +
  ylim(0,55) +
  labs (x = "Year", y = "Wind Speed (mph)") +
  ggtitle("April Wind Speeds 1935-2021") +
  theme_minimal() +
  geom_smooth( se =FALSE, method = 'lm', show.legend = FALSE) 
april_plot_35

#plot of April averages 1981-2021
april_plot_81 <- just_apr_81 %>%
  ggplot(aes(x = date, y = monthly_avg_spd ))+
  geom_point() +
  ylim(0,55) +
  labs (x = "Year", y = "Wind Speed (mph)") +
  ggtitle("April") +
  theme_minimal() +
  geom_smooth( se =FALSE, method = 'lm', show.legend = FALSE) 
april_plot_81

#May (5)
#making the data easier to work with (filtering by month, year)
just_may <- monthly_avg %>%
  filter(month == 5)
just_may_81 <- just_may %>%
  filter(year>=1981)
  
  
#plot of May averages 1935-2021
may_plot_35 <- just_may %>%
  ggplot(aes(x = date, y = monthly_avg_spd ))+
  geom_point() +
  ylim(0,55) +
  labs (x = "Year", y = "Wind Speed (mph)") +
  ggtitle("May Wind Speeds 1935-2021") +
  theme_minimal() +
  geom_smooth( se =FALSE, method = 'lm', show.legend = FALSE) 
may_plot_35

#plot of May averages 1981-2021
may_plot_81 <- just_may_81 %>%
  ggplot(aes(x = date, y = monthly_avg_spd ))+
  geom_point() +
  ylim(0,55) +
  labs (x = "Year", y = "Wind Speed (mph)") +
  ggtitle("May") +
  theme_minimal() +
  geom_smooth( se =FALSE, method = 'lm', show.legend = FALSE) 
may_plot_81

#June (6)
#making the data easier to work with (filtering by month, year)
just_june <- monthly_avg %>%
  filter(month == 6)
just_june_81 <- just_june %>%
  filter(year>=1981)
  
  
#plot of May averages 1935-2021
june_plot_35 <- just_june %>%
  ggplot(aes(x = date, y = monthly_avg_spd ))+
  geom_point() +
  ylim(0,55) +
  labs (x = "Year", y = "Wind Speed (mph)") +
  ggtitle("June Wind Speeds 1935-2021") +
  theme_minimal() +
  geom_smooth( se =FALSE, method = 'lm', show.legend = FALSE) 
june_plot_35

#plot of May averages 1981-2021
june_plot_81 <- just_june_81 %>%
  ggplot(aes(x = date, y = monthly_avg_spd ))+
  geom_point() +
  ylim(0,55) +
  labs (x = "Year", y = "Wind Speed (mph)") +
  ggtitle("June") +
  theme_minimal() +
  geom_smooth( se =FALSE, method = 'lm', show.legend = FALSE) 
june_plot_81

spring_MAMJ_plot <-grid.arrange(march_plot_81, april_plot_81, may_plot_81, june_plot_81, 
                                nrow = 2, 
                                top = "'Spring' Wind Speeds 1981-2021")
spring_MAMJ_plot
```

#Sen Slopes 
```{r}
##Theil-Sen Slopes for wind averages, by month, 1981-2021
#november
nov.sen <- sens.slope(just_nov_81$monthly_avg_spd, conf.level = 0.95)
View(nov.sen)

#december
dec.sen <- sens.slope(just_dec_81$monthly_avg_spd, conf.level = 0.95)
View(dec.sen)

#january
jan.sen <-sens.slope(just_jan_81$monthly_avg_spd, conf.level = 0.95)
View(jan.sen)


#february
feb.sen <- sens.slope(just_feb_81$monthly_avg_spd, conf.level = 0.95)
View(feb.sen)

#march
mar.sen <- sens.slope(just_mar_81$monthly_avg_spd, conf.level = 0.95)
View(mar.sen)

#april
april.sen <-sens.slope(just_apr_81$monthly_avg_spd, conf.level = 0.95)
View(april.sen)

#may
may.sen <- sens.slope(just_may_81$monthly_avg_spd, conf.level = 0.95)
View(may.sen)

#june
june.sen <-sens.slope(just_june_81$monthly_avg_spd, conf.level = 0.95)
View(june.sen)

################################################################################
#Theil sen slopes for seasonal data, annual data
#all done with monthly averages

#filtered for winter(Dec, Jan, Feb), 1981-2021
winter.sen<- sens.slope(monthly_winter$monthly_avg_spd, conf.level = 0.95)
View(winter.sen)

#filtered for spring (March, April, May), 1981-2021
spring.sen<- sens.slope(monthly_spring$monthly_avg_spd, conf.level = 0.95)
View(spring.sen)

#filtered for summer (June, July, Aug), 1981-2021
summer.sen<- sens.slope(monthly_summer$monthly_avg_spd, conf.level = 0.95)
View(summer.sen)

#filtered for fall (Sept, Oct, Nov), 1981-2021
fall.sen<- sens.slope(monthly_fall$monthly_avg_spd, conf.level = 0.95)
View(fall.sen)

#with all monthly averages 1981-2021
annual.sen<- sens.slope(monthly_since81$monthly_avg_spd, conf.level = 0.95)
View(annual.sen)

#with all monthly averages 1981-2013
#just did this one to compare the value I came up with with the value from 
#Cronin (2015), to make sure our Theil Sen values were the same
sen.81to13 <- TheilSen(monthly_81to13$year, monthly_81to13$monthly_spd_ms)
 

```

